### ISSUE TITLE
[GitHub CI] test がすべて実行されていないが、CI が pass してしまう

### ISSUE THREAD

**Issue by tksugimoto** [lerna-stack/lerna-app-library#26]
![image](https://user-images.githubusercontent.com/13145001/121324410-ac935900-c94b-11eb-8094-5e4cbc803b4c.png)

[docs: CHANGELOG.md に lerna-util-akka の変更を追記 · lerna-stack/lerna-app-library@dadc16d](https://github.com/lerna-stack/lerna-app-library/runs/2744688307#step:12:736)

> Error:  java.nio.file.NoSuchFileException: /home/runner/work/lerna-app-library/lerna-app-library/lerna-util-akka/target/scala-2.12/src_managed/main/scalapb/lerna/util/akka/protobuf/msg/AtLeastOnceDeliveryRequest.scala  

## ローカルでのtest結果
```sh
$ sbt clean +lerna-util-akka/test
```
```
[info] AtLeastOnceDeliveryTypedSpec:
[info] askTo()
[info] - should 宛先に到達保証用メッセージを送信できる *** FAILED ***
[info]   java.lang.UnsupportedOperationException: cannot create top-level actor from the outside on ActorSystem with custom user guardian
(略)
```
```
[info] Tests: succeeded 21, failed 6, canceled 0, ignored 0, pending 0
[info] *** 6 TESTS FAILED ***
```

## GitHub CI yml

```yml
      - name: Run tests
        continue-on-error: true # results are reported by action-junit-report
        run: sbt coverage +test

      - name: Publish test report
        uses: mikepenz/action-junit-report@v2
        with:
          check_name: ScalaTest Report
          report_paths: 'lerna-*/target/scala-*/test-reports/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

## 解決すべき問題
1. `/home/runner/work/lerna-app-library/lerna-app-library/lerna-util-akka/target/scala-2.12/src_managed/main/scalapb/lerna/util/akka/protobuf/msg/AtLeastOnceDeliveryConfirm.scala (No such file or directory)` が出ていること (lerna-app-library の test が skip される)
1. 一部test がskip されても検知できていないこと

## 問題だったPR (エラーを検知できていないPR)
- https://github.com/lerna-stack/lerna-app-library/pull/7 ```Typed/lerna util akka by tksugimoto · Pull Request #7 · lerna-stack/lerna-app-library```
- Scala 2.13 対応 https://github.com/lerna-stack/lerna-app-library/pull/18 ```クロスビルド (Scala 2.13.4, Scala 2.12.12) by xirc · Pull Request #18 · lerna-stack/lerna-app-library```
  - [Use filter instead · lerna-stack/lerna-app-library@6c9513d](https://github.com/lerna-stack/lerna-app-library/runs/2707003099#step:12:1527)
    > Error:  java.nio.file.NoSuchFileException: /home/runner/work/lerna-app-library/lerna-app-library/lerna-util-akka/target/scala-2.13/src_managed/main/scalapb/lerna/util/akka/protobuf/msg/AtLeastOnceDeliveryRequest.scala
